# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0
    - run: git fetch origin $GITHUB_HEAD_REF
    - run: git switch $GITHUB_HEAD_REF
    - run: git branch --list
    - run: git submodule foreach --recursive git config --local gc.auto 0
    - run: git config user.email "robot@example.com"
    - run: git config user.name "Myname Willbe Discarded"
    - run: git merge main
    - run: git branch --list
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npx lerna exec -- rm -rf package-lock.json
    - run: env
    - run: GITHUB_ACTIONS='' npm run ci:test-all
    - run: npm run ci:publish-check
